import "../styles/globals.css";
import { Todo } from "../types";
import Aside from "./aside";

async function getData() {
  const res = await fetch("https://jsonplaceholder.typicode.com/todos");
  return res.json() as Promise<Todo[]>;
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const data = await getData();
  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className="container mx-auto">
        <header className="pt-3 pb-6">
          <p className="text-xl">JSON Placeholder - Next 13</p>
        </header>
        <div className="grid grid-cols-2 gap-8">
          <aside className="sticky top-0 overflow-y-auto h-56">
            <Aside data={data} />
          </aside>
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
